diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.email=hijaponjusten030119@gmail.com
user.name=justenhijapon
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.oldorigin.url=https://github.com/leadmonkeyboy007/eStore.git
remote.oldorigin.fetch=+refs/heads/*:refs/remotes/oldorigin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main
remote.neworigin.url=https://github.com/justenhijapon/eStore_temp.git
remote.neworigin.fetch=+refs/heads/*:refs/remotes/neworigin/*
remote.origin.url=https://github.com/justenhijapon/eStore_temp.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
